[package]
name = "sms-gateway-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
time = { version = "0.3.5", features = ["parsing"] }
lazy_static = "1.4.0"
